export const ABORT_REQUEST = 'ABORT_REQUEST';

export const AUTHENTICATION = 'AUTHENTICATION';

export const ENABLE_ABORT_REQUEST = 'ENABLE_ABORT_REQUEST';

export const GET_DONE = 'GET_DONE';

export const GET_PAGE = 'GET_PAGE';

export const GET_PENDING_RELEASE_DATE_ALBUM = 'GET_PENDING_RELEASE_DATE_ALBUM';

export const GET_PENDING_SPOTIFY_ID = 'GET_PENDING_SPOTIFY_ID';

export const GET_TO_DO = 'GET_TO_DO';

export const GET_PENDING_TRACK_NUMBER = 'GET_PENDING_TRACK_NUMBER';

export const LOADING = 'LOADING';

export const NAVIGATION = 'NAVIGATION';

export const POP_TO_DO = 'POP_TO_DO';

export const RESTORE_FROM_LOCAL_STORAGE = 'RESTORE_FROM_LOCAL_STORAGE';

export const SET_ACTION_DATA = 'SET_ACTION_DATA';
